import os
from dotenv import load_dotenv

# Load environment variables from a .env file in the project root
load_dotenv()

# --- Core Parameters ---
# Your Mapillary Access Token (loaded from the .env file)
ACCESS_TOKEN = os.getenv("MAPILLARY_ACCESS_TOKEN")
# The Mapillary creator username you want to get data from
CREATOR_USERNAME = "OMDTZ1"
# Distance threshold for considering a Mapillary image useful for a building
SVI_DISTANCE_THRESHOLD_METERS = 30
# Set to True to draw a red line on the full SVI panorama for debugging
DRAW_RED_LINE_ON_SVI = False
# Set to True to save SVI images with building masks for debugging brightness calculation
SAVE_DEBUG_MASKED_IMAGES = False

# --- Input Data Paths ---
# Directory for all source data
DATA_DIR = "data"
# The main boundary file for the area of interest
MSIMBAZI_EXTENT_FILE = os.path.join(DATA_DIR, "Msimbazi_extent.geojson")
# OSM road and building files
OSM_ROADS_FILE = os.path.join(DATA_DIR, "OSM_roads.gpkg")
OSM_BUILDINGS_FILE = os.path.join(DATA_DIR, "OSM_residential_buildings.gpkg")
# Input UAV orthomosaic raster file
UAV_RASTER_FILE = os.path.join(DATA_DIR, "Msimbazi_image.tif")
# Path to your manually created ground-truth labels for classification
CLASSIFICATION_LABELS_FILE = os.path.join(DATA_DIR, "osm_labels.csv")

# --- Output Data Paths ---
# Main directory for all generated output
OUTPUT_DIR = "output"
# Subdirectory to store individual tile data from Mapillary
MAPILLARY_TILES_DIR = os.path.join(OUTPUT_DIR, "mapillary_tiles")
# Final combined Mapillary points file
COMBINED_MAPILLARY_FILE = os.path.join(OUTPUT_DIR, "mapillary_points_combined.gpkg")
# Buildings that intersect with the buffered roads
INTERSECTING_BUILDINGS_FILE = os.path.join(OUTPUT_DIR, "buildings_near_roads.gpkg")
# Final output of visible buildings
VISIBLE_BUILDINGS_FILE = os.path.join(OUTPUT_DIR, "visible_buildings_final.gpkg")
# Output directory for the cropped & masked UAV image chips
CROPPED_UAV_CHIPS_DIR = os.path.join(OUTPUT_DIR, "cropped_uav")
# Output directory for the full downloaded SVI panoramas
SVI_IMAGES_DIR = os.path.join(OUTPUT_DIR, "svi_panoramas")
# Output directory for the cropped SVI images
CROPPED_SVI_CHIPS_DIR = os.path.join(OUTPUT_DIR, "cropped_svi")
# Output directory for labeled training images generated by stage 6a
LABELS_DATA_DIR = os.path.join(OUTPUT_DIR, "labels_data")
# Directory for Mapillary object detection CSVs
MAPILLARY_DETECTIONS_DIR = os.path.join(OUTPUT_DIR, "mapillary_detections")
# Path to the CSV with building-to-image centerline calculations
CENTERLINE_DATA_FILE = os.path.join(OUTPUT_DIR, "centerline_data.csv")
# Intermediate file that stores all engineered features before final formatting
FEATURES_MASTER_FILE = os.path.join(OUTPUT_DIR, "features_master.csv")
# Final output files for model training
FINAL_CLASSIFICATION_FILE = os.path.join(OUTPUT_DIR, "CV_classdata.csv")
FINAL_REGRESSION_FILE = os.path.join(OUTPUT_DIR, "CV_regression.csv")
# Main directory for all visualization outputs
VISUALIZATION_DIR = os.path.join(OUTPUT_DIR, "visualizations")
# Subdirectory for Grad-CAM outputs
GRADCAM_OUTPUT_DIR = os.path.join(VISUALIZATION_DIR, "gradcam")

# --- Processing Parameters ---
# Size of the grid tiles for fetching Mapillary data (in meters)
TILE_SIZE_METERS = 100
# Buffer distance for roads (in meters)
ROAD_BUFFER_METERS = 20
# Maximum distance to search for a Mapillary point from a building (in meters)
NEIGHBOR_SEARCH_RADIUS_METERS = 25
# The final filter distance for a building to be considered "nearby" a point
NEARBY_DISTANCE_METERS = 20
# Threshold for removing UAV image chips with too few non-black pixels
NON_BLACK_PIXEL_THRESHOLD = 3000

# --- Mapillary API Fields ---
MAPILLARY_FIELDS = ",".join([
    "id", "geometry", "computed_geometry", "camera_type", "compass_angle",
    "computed_compass_angle", "altitude", "computed_altitude", "exif_orientation",
    "height", "width", "is_pano", "make", "model", "thumb_original_url",
    "atomic_scale", "sequence"
])

# --- Feature Engineering Parameters ---
# Target object classes for SVI brightness calculation
TARGET_CLASSES = {
    'construction--barrier--wall': 'orange',
    'construction--structure--building': 'red',
}
# List of the task/category folders to process for classification
LABEL_CATEGORIES = [
    "material_wall", "number_of_floors", "vegetation",
    "structural_openness", "material_rooftop"
]

